### ISSUE TITLE
Transaction doesn't work if there's a call to an additional suspend function

### ISSUE THREAD

**Issue by ronzeidman** [line/kotlin-jdsl#135]
```kotlin
				factory.transactionWithFactory { session, _ ->
					val entity = TestEntity(title = Title("should succeed"))
					session.persist(entity)
						.chain(Supplier { session.flush() })
						.replaceWith(entity)
						.awaitSuspending()
					delay(2000)
				}
```
^ this code breaks, this means that I can't run a transaction and call external suspend function without breaking the code
Is there something I'm missing? 
how can I do multiple things in a transaction like - get -> async big calculation -> save

**Comment by shouwn** [comment]
Hi @cj848 Could you check this? I don't know much about hibernate reactive

**Comment by cj848** [comment]
https://github.com/hibernate/hibernate-reactive/blob/main/documentation/src/main/asciidoc/reference/introduction.adoc#sessions-and-vertx-contexts
Please refer to the link. In hibernate reactive internal query execution scope, separate parallel execution or execution through another thread is prohibited.
If a separate thread operation is entered within the db operation, hibernate reactive does not allow it at all because it is difficult to maintain a normal session. Even if your intention is an operation unrelated to db, it seems to be the intention of the framework developer to prevent the possibility of problems. This part is not something I can do anything about. I'm sorry I couldn't help. If you understand, please close the comment.

**Comment by cj848** [comment]
Since there is no reply for a long time, I will close it. If you have further questions, please proceed to a new issue.

**Comment by namjug-kim** [comment]
This is a closed issue, but i have same problem and it was solved by **vertx-lang-kotlin-coroutines**

```
factory.transactionWithFactory { session, _ ->
    CoroutineScope(Vertx.currentContext().dispatcher()).launch {
        val entity = TestEntity(title = Title("should succeed"))
        session.persist(entity)
            .chain(Supplier { session.flush() })
            .replaceWith(entity)
            .awaitSuspending()
        delay(2000)
    }
}
```

https://vertx.io/docs/vertx-lang-kotlin-coroutines/kotlin/
> The vertx.dispatcher() returns a coroutine dispatcher that execute coroutines using the Vert.x event loop.

**Comment by cj848** [comment]
wow.. Oh... I guess this is good practice. thanks. I will make it into a document for reference. Thank you
