### ISSUE TITLE
Inserting data

### ISSUE THREAD

**Issue by milgner** [line/kotlin-jdsl#229]
At the moment, working with data requires two different interfaces: 

- the plain Hibernate Session Factory for inserting data
- the `HibernateMutinyReactiveQueryFactory` (which receives the session factory as a dependency) for reading data

I think it would be nice to only require one class to interact with data.

Unfortunately the `sessionFactory` in `HibernateMutinyReactiveQueryFactory` is marked as `private`. A minimalistic approach would be to make this `protected` which would allow extending this functionality via extension functions a breeze.

Alternatively, what do you think about adding some basic `persist` functionality as a facade to this library?

**Comment by cj848** [comment]
Thank you for your comments. I thought about that part, but in the end I didn't include it. The reason we thought so was because we thought it would be inappropriate to add a save function to the function that executes and creates only simple queries. It seems that the reason is the same as that there is no persist function in the JPA Criteria API.

However, in the case of hibernate reactive query, since the query can be executed only within the scope, the session had to be passed so that it can be processed separately. In fact, I wouldn't have included it if the query could have been performed in the same session without passing it. That's why there is no helper method like withSession in ReactiveQueryFactory .

**Comment by milgner** [comment]
Sounds reasonable :+1: In that case I'll probably build a facade around both of these objects that can be injected into database-aware parts of the code. Thank you for the quick feedback and an awesome project - using the plain Criteria API is a real PITA and having expressive, type-safe queries using kotlin-jdsl is much more pleasant to work with!
