### ISSUE TITLE
FindPage QueryUtils.createCountQueryFor

### ISSUE THREAD

**Issue by maxzycon** [line/kotlin-jdsl#491]
hi i try to using pagination with v3 

```kotlin

  override fun FindAllPaginatedAdmin(
    pageable: Pageable,
    search: String,
    status: List<Int>,
    dateStart: LocalDateTime?,
    dateEnd: LocalDateTime?
  ): Page<OrderClaimAdminPaginatedRes?> {
    val resp = fOrderClaimBatchJPARepository.findPage(pageable) {
      val parent = entity(FOrderClaimBatchEntity::class)
      val query = selectNew<OrderClaimAdminPaginatedRes>(
        parent(FOrderClaimBatchEntity::id),
        parent(FOrderClaimBatchEntity::batchNo),
        path(FExpedisiEntity::description),
        parent(FOrderClaimBatchEntity::imagePath),
      ).from(
        parent,
        leftJoin(FOrderClaimBatchEntity::expedition),
      )
      query.orderBy(parent(FOrderClaimBatchEntity::id).desc())
      query
    }
    return resp
  }

```

Here is my DTO 
```kotlin
data class OrderClaimAdminPaginatedRes(
  val id: Int,
  val batchNo: String,
  val expeditionName: String?,
  val imagePath: String?,
)
```

but i have issue when hit endpoint show error like this 

``
"Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: 'java.lang.String org.springframework.data.jpa.repository.query.QueryUtils.createCountQueryFor(java.lang.String, java.lang.String, boolean)'"
``

i thought i have add all dependency for spring data javax, thankyou

**Comment by shouwn** [comment]
Kotlin JDSL uses QueryUtils in Spring Data to support `Pageable` of Spring Data:
https://github.com/line/kotlin-jdsl/blob/main/support/spring-data-jpa-javax/src/main/kotlin/org/springframework/data/jpa/repository/query/QueryUtilsAdaptor.kt

But when I looked at the Spring changelog, the class had disappeared for a certain version. Then someone created an issue, and QueryUtils was recreated:
https://github.com/spring-projects/spring-data-jpa/issues/2812

So, to use Pageable in Kotlin JDSL, there are minimum requirements for Spring version.
For Spring 2.XX: org.springframework.data:spring-data-jpa:2.7.9
For Spring 3.XX: org.springframework.data:spring-data-jpa:3.0.3

I suspect the error is caused by your version of Spring being lower.

**Comment by maxzycon** [comment]
thank you @shouwn, i update to 2.7.9 ``pageable`` works well
