### ISSUE TITLE
Do you support CriteriaBuilder.treat() ?

### ISSUE THREAD

**Issue by chanqun** [line/kotlin-jdsl#51]
I can't find CriteriaBuilder.treat() in jdsl

ref: 
https://www.logicbig.com/tutorials/java-ee-tutorial/jpa/criteria-api-downcasting-with-treat-method.html

Can you support this?

**Comment by shouwn** [comment]
-- english
We have not considered query support for the polymorphic entity model. In addition to treat method, I have found methods to support polymorphic model such as type.

It seems difficult to apply immediately because we need to figure out how to use polymorphic models in common and what usage users want. Also we are currently working on another task, so it will be difficult to proceed with this task immediately.

I'll let you know when we start working on it. 

> It would be helpful for us to create an interface if you could create a sample of the queries you create in relation to the polymorphic model.

Thank you for your Issue.

-- korean
다형성 entity 모델에 대한 쿼리 지원을 생각하지 못 했습니다. 관련해서 treat 외에도 type과 같은 메소드도 있는 것을 확인했습니다.

실제 다형성을 활용할 수 있는 메소드가 무엇이 있고, 각 메소드가 어떤 식으로 사용되는지 파악해야 하기 때문에 바로 적용은 어려울 것으로 보입니다.

이 외에도 현재 kotlin-jdsl 외에 다른 작업을 진행하고 있기 때문에 바로 이 테스크를 진행하는 것은 어려울 것으로 보입니다. 저희가 작업을 시작하게 되면 말씀드리겠습니다. 

> 만약 다형성 모델을 기반으로 작성한 쿼리 샘플을 공유해주시면 저희가 인터페이스 잡는데 도움이 될 것 같습니다. 

문의 주셔서 감사합니다.

**Comment by cj848** [comment]
implement treat in version 2.0.2.RELEASE.

-- korean
2.0.2 버전에 treat 기능이 릴리즈 되었습니다.
