### ISSUE TITLE
Support for java entity with private setter

### ISSUE THREAD

**Issue by jbl428** [line/kotlin-jdsl#517]
## Suggestion

This project is a Kotlin library, but I think it can also be used in projects that use both Java and Kotlin together.
(Especially, entities are written in Java, while other parts are in Kotlin.)

Because even in Java classes, we can obtain `KClass` and `KProperty`

```java
public class Sample {
    public String name;
}
```

```kt
    val kclass: KClass<Sample> = Sample::class
    val kproperty: KMutableProperty1<Sample, String> = Sample::name
```

However, there is an issue with obtaining `KProperty` of private fields in JPA entities, 
as JPA entities typically apply private setters to their fields.

```java
public class Sample {

    private String name;

    public String getName() {
        return name;
    }
}

```

```kt
    val kclass: KClass<Sample> = Sample::class // no issue
    val kproperty = Sample::name // error
   // The feature "references to synthetic java properties" is only available since language version 2.1
```

The error message indicates that there are plans to allow obtaining KProperty from private fields even in Kotlin 2.1, 
but I believe this is a distant future.

So, I suggest adding a feature to infer column names through getters(KFunction1) instead of properties.

## Plan

- Change `JpqlEntityProperty` and `JpqlPathProperty` property.

```kt
@Internal
data class JpqlEntityProperty<T : Any, V> internal constructor(
    val entity: Entity<*>,
    val property: Property<in T, V>, // change to data class or `Propertieable` interface (not sure what is best)
) : Path<V & Any>

data class Property<T, V>(val name: String)
```

- Add override methods of `path` and `invoke` for `KFunction1`

```kt
  @SinceJdsl("3.0.0")
  fun <T : Any, V> path(entity: Entity<T>, getter: KFunction1<T, @Exact V>): Path<V & Any> {
      return JpqlEntityProperty(entity, Property<T, V>(getter.getPropertyName))
  }
```

- Infer the property name from `KFunction`

But, I can not sure it will be work as expected.
I would appreciate any opinion on this :)

## Inspired by

Codes for Kotlin support of Fixture Monkey project.

[getPropertyName](https://github.com/naver/fixture-monkey/blob/29413f42e42ad9eae5168e63f444cefefeadefa7/fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/type/KotlinTypes.kt#L128C1-L138)

**Comment by shouwn** [comment]
There have already been questions on [Discord](https://discord.com/channels/1087271586832318494/1120991684512186389/1151156532378079252) about Java support, so I think this would be a reasonable feature to support. 

As you know, `JpqlEntityProperty` does not need to have a KProperty as a field, because it only uses the name of the KProperty. I would probably use String as the type for the property field if I were to modify JpqlEntityProperty to support this feature. This is not an odd situation because `jakarta.persistence.criteria.Path#get` already has an interface that takes only a single String as a parameter. 

What I'm worried about is how to get the name of the property correctly by looking at the name of the method. 

In fixture-monkey, it only compares if the prefix has a get and an is. This should be possible because it uses Kotlin-generated getters and setters. Because when a class has a field of type Boolean named isTest, lombok creates an `isTest` getter if the type is primitive or a `getIsTest` getter if the type is a wrapper. Similarly, the naming of getters and setters depends on the nature of the library. I'm still not sure how to interpret this.

It would be good if someone could give me some clear rules regarding getters and setters in java, then I could support this.

**Comment by jbl428** [comment]
@shouwn 
I understand. then how about adding a functionality that library user provides theirs own property resolution strategy?

- suggestion 1

Add a method like `pathByGetter` that takes `KFunction1` as argument.
To use that method, user must register some `PropertyResolver` to `JpqlRenderContext`.

- suggestion 2

Provide some support module for library specific property resolution. (like kotlin-jdsl-lombok-support)

- suggestion 3

Just add a override `path` method that takes `String` as property name and `KClass`.
then use can create its own extension function that takes `KFunction1` and resolve property name.

**Comment by shouwn** [comment]
@jbl428 Thank you for suggestions!

The simplest approach is suggestion 3, but I don't think it's much different than creating custom expressions and serializers. The support module in suggestion 2 would also require a new extension point.

I've been thinking more about your suggestion 1. 

How about changing the property in `KEntityProperty` to `KCallbale` instead of `KProperty`, and having the `Expressions` factory class receive `KFunction1` and `KProperty1`? If so, we can create new extension point in `JpqlIntrospector` to introspect the `KCallable` to get `KPropertyDescription`. 

```kotlin
@Internal
data class JpqlEntityProperty<T : Any, V> internal constructor(
    val entity: Entity<*>,
    val property: KCallable<V>,
) : Path<V & Any>

@SinceJdsl("3.0.0")
interface JpqlIntrospector {
    @SinceJdsl("3.0.0")
    fun introspect(type: KClass<*>): JpqlEntityDescription?

    @SinceJdsl("3.1.0")
    fun introspect(property: KCallable<*>): JpqlPropertyDescription?
}

@Internal
class JpqlEntityPropertySerializer : JpqlSerializer<JpqlEntityProperty<*, *>> {
    override fun handledType(): KClass<JpqlEntityProperty<*, *>> {
        return JpqlEntityProperty::class
    }

    override fun serialize(part: JpqlEntityProperty<*, *>, writer: JpqlWriter, context: RenderContext) {
        val introspector = context.getValue(JpqlRenderIntrospector)
        val property = introspector.introspect(part.property)

        writer.write(part.entity.alias)
        writer.write(".")
        writer.write(property.name)
    }
}
```

In this way, the Kotlin JDSL can provide the user with a default implementation, and the user can override the JpqlIntrospector using JpqlRenderModule if they don't like the default implementation.

**Comment by jbl428** [comment]
@shouwn 
> but I don't think it's much different than creating custom expressions and serializers.

Ah, I see. With custom expressions and serializers, users already can add a support for java getter.
I missed that part :)
I think providing example code or guidance through documentation could be a solution instead of adding additional features.
However, in my opinion, your idea provides a more elegant and convenient feature for users.

> In this way, the Kotlin JDSL can provide the user with a default implementation

Is there a strategy you have in mind for the default implementation? (maybe lombok you mentioned?)

**Comment by shouwn** [comment]
I'll make the default implementation follow Kotlin's policy. When Kotlin generates a getter, it prefixes the getter with `get', regardless of whether the field is boolean or not. If the field name starts with `is`, Kotlin keeps it.

**Comment by jbl428** [comment]
Thank you for your response.
If you don't mind, could i take this one?

**Comment by shouwn** [comment]
Sure! Thanks for your help! I'll change the assignee to you.

**Comment by jbl428** [comment]
> How about changing the property in KEntityProperty to KCallbale instead of KProperty, and having the Expressions factory class receive KFunction1 and KProperty1?

I have a question while working. 

Is it intended to add methods that take `KFunction1` and `KProperty1` to the `Expressions` factory class? 
Since, there is already a method in `Path` that takes `KProperty1`, so I'm curious why it needs to be created in `Expressions`. 

If it needs to be created in `Expressions`, should additional methods that take `KProperty1` be added, besides`KFunction1`?

**Comment by shouwn** [comment]
@jbl428 
Sorry, I was mistaken, I thought the `Expressions` factory was creating the paths. As you said, it only need to be in the `Paths` factory. Thank you for confirming my mistake.
