### ISSUE TITLE
Empty OR predicate renders '0 = 1' instead of documented '1 = 1'

### ISSUE THREAD

**Issue by vladimirfx** [line/kotlin-jdsl#571]
See `JpqlOrSerializer.kt:22`

**Comment by shouwn** [comment]
Hi vladimirfx. Thank you for looking at the documentation. 

I confused you by using the wrong vocabulary because I'm not a native English speaker.

> If all `Predicate` passed to `and()` and `or()` is null or empty, `and()` will be interpreted as `1 = 1` and `or()` will be interpreted as `0 = 1`.

I wanted to write that in the case of OR, it would render as `0 = 1`. Do you have any suggestions on how to modify the above text to make it easier to understand?

**Comment by vladimirfx** [comment]
Why empty OR is rendered as false? OR is by definition more permissive composition than AND. But for empty predicates is becoming false. Very frustrating.
I think code should be corrected, not the documentation.

**Comment by shouwn** [comment]
The reason Kotlin JDSL renders `AND` as 1 = 1 and `OR` as 1 = 0 is because we adopted the concept from Kotlin and the Criteria API. 

- Kotlin implements these concepts in `Iterable<T>.all()` and `Iterable<T>.any()`
- Criteria API implements these concepts in `CriteriaBuilderImpl.and(Predicate... restrictions)` and `CriteriaBuilderImpl.or(Predicate... restrictions)`. 

In the case of `AND`, I found that the concept of "Vacuous truth" is implemented, but I don't know what concept is adopted in the case of `OR`.

**Comment by vladimirfx** [comment]
In this case, there is NO active condition. Current implementation leads to 100% empty query results - It is logically absurd. The user must check all its `OR` null conditions before giving it to DSL.

**Comment by shouwn** [comment]
I think an empty query result is sometimes good and sometimes bad depending on the use case. For example, it can be good for delete queries. You can write code to not delete anything if there is no `condition`.

I don't think this is something that can be generally determined.

Kotlin JDSL is based on Kotlin and JPA. Therefore, I think it would be better to make it follow Kotlin's and JPA's conventions to avoid confusing users.

If you want the `OR` to be true, I can provide a `conjunction` and `disjunction` function in DSL. This allows you to define your own functions, such as `fun orElseConjunction()`, that combine `or()` and `conjunction()`.

**Comment by vladimirfx** [comment]
So, fixing the documentation.

**Comment by shouwn** [comment]
> If all Predicate passed to and() and or() is null or empty, and() will be interpreted as 1 = 1 and or() will be interpreted as 0 = 1.

So, how do I fix it?

**Comment by vladimirfx** [comment]
Fix documentation, I think:

`com/linecorp/kotlinjdsl/dsl/jpql/Jpql.kt:1911`

But behavior is very annoying - empty predicate id `FALSE`. I understand that such behavior is in sync with `CriteriaBuilder.or` but it ruins my intuition ))

Thank you!

**Comment by shouwn** [comment]
Oh, you meant Kotlin Doc, this is my fault. I'll deploy this as a hotfix.
