### ISSUE TITLE
Entity 객체 전체를 넘겨서 업데이트 하는 쉬운 방법이 있나요?

### ISSUE THREAD

**Issue by ShindongLee** [line/kotlin-jdsl#67]
안녕하세요!
Entity 객체 전체를 넘겨서 업데이트 하는 쉬운 방법이 있나요?

JpaRepository 에서는 아래처럼 쉽게 업데이트가 가능했습니다.
```kotlin
val update = repository.save(bus) // S save(S entity) 
```
kotlin-jdsl 로는, 아래처럼 써야하는데요,
```kotlin
fun save(bus: Bus): Bus {
       queryFactory.updateQuery<Bus> {
            where(col(Bus::id).equal(bus.id))
            setParams(col(Bus::columnA) to bus.columnA)
            setParams(col(Bus::columnB) to bus.columnB)
        }.executeUpdate()

        return queryFactory.singleQuery<Reward> {
            select(entity(Bus::class))
            from(entity(Bus::class))
            where(col(Bus::id).equal(bus.id))
        }
}
```
Bus Entity Class 에 컬럼이 추가될때마다 save 함수를 고쳐야 했습니다.

저는

1. Entity Object 를 넘겨서 모든 컬럼을 업데이트를 하고 싶습니다.
2. 업데이트 된 객체를 반환 하고 싶습니다.

위 예제 코드보다 간단한 방법이 있나요?

(참고로 entityManager.merge 를 사용하지 않는 이유는 update 할때 where 조건을 커스터마이징하기 위함입니다)

**Comment by cj848** [comment]
-- korean
해당 부분에 대해서는 오해하고 있는 것 같아서 말씀드리자면, JPA 의 update 쿼리와 dirty check 는 같은 선상에 볼 수 없습니다. 

사용하신 코드의 원래 의도라면 Bus 라는 엔티티를 로드 했을수도 있고 안 했을수도 있습니다만, 결과적으로 값이 변경된 엔티티 값을 리턴하고 싶어하는 것으로 볼 수 있습니다. 

만약 그런 사용 방법이라면 update 쿼리문을 쓰시는것보다 findById 와 같이 엔티티를 Persistence Context 에서 꺼내와서 처리하시는게 더 좋습니다. 만약 Persistence Context 에 Bus엔티티가 들어있다면 별도 db fetch 동작 없이 캐시에서 읽어올 것이고 그후에 값을 직접 변경하는 로직을 사용하시면 됩니다.

일단 메소드 이름은 save 인데 내부 동작은 save 가 아닌 특정 컬럼을 업데이트 하는 방식이므로 메소드 이름도 적합한지에 대해 고민해보시면 좋을 것 같습니다.

만약 저라면 save 라는 이름을 가진 메소드가 아닌 updateColumnAB 혹은 비지니스 동작에 해당하는 이름을 붙이고 Bus 객체를 받을 경우 Spring Data JPA에서 존재하는 findByIdOrNull 메소드로 객체를 불러오고 값을 변경한 후에 자동으로 해당 객체를 직접 리턴하고 사용할 것 같습니다. 어차피 트랜잭션이 종료되면 해당 객체와 디비는 동기화가 됩니다.

즉, 지금 사용하시는 jdsl 의 사용 방법은 JPA 의 기본 사용방법에 어긋납니다.

-- english
As I seem to have misunderstood about that part, to tell you, JPA's update query and dirty check cannot be seen on the same line.

According to the original intent of the code you used, you may or may not have loaded an entity called Bus , but as a result, you can see that you want to return the value of an entity whose value has changed.

If that is the case, it is better to take the entity out of Persistence Context and process it like findById rather than using the update query statement. If there is a Bus entity in the Persistence Context, it will be read from the cache without a separate db fetch operation, and then you can use the logic to directly change the value.

First of all, the method name is save , but the internal operation is to update a specific column rather than save , so it would be good to think about whether the method name is appropriate.

If it is me, not a method named save, but updateColumnAB or a name that corresponds to a business action and receives a Bus object, call the object with the findByIdOrNull method existing in Spring Data JPA, change the value, and then automatically direct the object. It seems to return and use. When the transaction ends anyway, the object and DB are synchronized.

In other words, the method of using jdsl that you are currently using goes against the basic method of using JPA.

**Comment by ShindongLee** [comment]
@cj848 안녕하세요, 먼저 친절한 답변 감사드립니다.

질문이 조금 부정확했던 것 같아서 추가 설명을 드리고 싶습니다.

>만약 그런 사용 방법이라면 update 쿼리문을 쓰시는것보다 findById 와 같이 엔티티를 Persistence Context 에서 꺼내와서 처리하시는게 더 좋습니다. 만약 Persistence Context 에 Bus엔티티가 들어있다면 별도 db fetch 동작 없이 캐시에서 읽어올 것이고 그후에 값을 직접 변경하는 로직을 사용하시면 됩니다.

Update를 할때 추가적인 where 조건을 주고 싶어서 jdsl 쿼리 사용하고 싶은데, 그냥 dirty check를 사용하게 되면 pk로만 찾아서 업데이트를 하기때문에 jdsl 쿼리로 직접 업데이트하고자 합니다. 왜 pk 외의 where 조건이 필요하냐하면, db가 파티셔닝되어있어 파티션키를 업데이트 쿼리의 where 조건에 넣고 싶어서 입니다. 넣지 않으면 모든 파티션에 pk로 찾으려는 쿼리가 날라가서요!

> 일단 메소드 이름은 save 인데 내부 동작은 save 가 아닌 특정 컬럼을 업데이트 하는 방식이므로 메소드 이름도 적합한지에 대해 고민해보시면 좋을 것 같습니다.

이건 설명이 부족했는데, CrudRepository 의 save 를 그대로 jdsl 로 구현하고자해서 이름을 가져왔습니다. 의도한 동작은 모든 컬럼을 업데이트하는 것입니다. 예시로 든 Bus 의 컬럼은 아래처럼 columnA, columnB 만 있다고 가정했습니다. 
```kotlin
data class Bus(val columnA: String, val columnB: String)
```
그래서 위 코드는 모든 컬럼을 잘 업데이트하지만, 예를들어 columnC 가 추가된다면, 본문의 update 함수도 수정해줘야하는 문제가 있어서, 모든 컬럼을 업데이트 하는 메소드가 없나 궁금했습니다.

혹시 한번 더 답변 주실수 있으실까요? 감사합니다.

**Comment by cj848** [comment]
우선 Criteria 의 Update/delte 쿼리에 대한 사용 예에 대해서 먼저 말씀드리는것이 이해에 도움이 될 것 같아서 말씀드리겠습니다.

1. update/delete 쿼리는 대상 객체를 Persistence Context에 로드하지 않은 상태에서 조건으로 변경/삭제 만 진행하고 해당 엔티티를 리턴 받지 않을때 사용하는게 권장되며 그렇지 않을 경우 JPA 의 기본 스펙인 dirty check 를 이용해서 엔티티를 로드하고 처리하는게 더 성능상의 이득이 큽니다. 

2. id 하나만 가지고 한개의 객체를 업데이트 한다고 하면 1번 예에서 별도의 연산을 통해 값을 한번의 operation 으로 업데이트 하고 싶을때 사용하시면 됩니다.

다시 결론을 말씀드리면 최초에 저에게 알려주셨던 save 방식이 훨씬 JPA 의 사용 예에 적합합니다. 굳이 jdsl 을 사용하실 상황이 아닌것으로 판단됩니다.

JDSL 은 쿼리를 생성하고 실행하는데 최적의 라이브러리이며 그 외적인 용도라면 JPA 본연의 기능을 쓰시는게 더 이득이 됩니다. 즉, EntityManager 를 통해 원하시는 바를 시행하시는게 더 이득입니다.

-- english
First of all, I think it will be helpful for understanding to tell about the usage example of Criteria's Update/delte query.

1. The update/delete query is recommended to be used when the target object is not loaded into the Persistence Context and only change/delete conditionally and the corresponding entity is not returned. Loading and processing entities has more performance gains.

2. If you want to update one object with only one id, you can use it when you want to update the value in one operation through a separate operation in Example 1.

In conclusion, the save method you told me in the beginning is much more suitable for the use case of JPA. It is judged that there is no need to use jdsl.

JDSL is an optimal library for creating and executing queries, and for other purposes, it is more beneficial to use the original function of JPA. In other words, it is more beneficial to implement what you want through the EntityManager .

**Comment by cj848** [comment]
-- korean
참고로 Criteria 를 이용한 update,delete 를 수행할 경우 Persistence Context 가 비워지게 됩니다. 그 이전의 다른 동작들이 있었고 Persistent Context 동작으로 처리하던 부분이 있다면 디비에 즉시 반영됩니다. 그러므로 성능에 크게 도움되지 않습니다.

-- english
For reference, if update or delete using Criteria is performed, Persistence Context is empty. If there were other actions before that, and there were parts that were handled as Persistent Context actions, they are immediately reflected in DB. So it doesn't do much for performance.

**Comment by ShindongLee** [comment]
@cj848 답변 감사드립니다.
