### ISSUE TITLE
Proposal: Adding EXTRACT function

### ISSUE THREAD

**Issue by erie0210** [line/kotlin-jdsl#674]
In the JPA datetime specification document, there is a function called extract_datetime_part, but it seems that there is no implementation in the library. If it's indeed missing, may I proceed with working on it? [Link](https://jakarta.ee/specifications/persistence/3.1/jakarta-persistence-spec-3.1.html#a5304)

**Comment by waahhh** [comment]
@shouwn 
I've been thinking about implementing the EXTRACT function before, and I did some tests beforehand, but I've put it on hold for now due to work. but I saw an issue related to EXTRACT function support, so I would like to inquire.

When I checked, I found that some of the JPA implementations(Hibernate, EclipseLink) supported by Kotlin JDSL are not compliant with the jakarta specification (extract_datetime_part), and some features are not yet supported. Also, some features do not work correctly with the current Kotlin JDSL project Test environment configuration (h2 driver, dialect).

In this case, if Kotlin JDSL provides an JDSL API that complies with the jakarta specification, it may not work correctly at runtime if the user uses a JPA implementation that does not comply with the specification or uses features that are not yet supported, but is it okay for Kotlin JDSL to just provide a JDSL API that complies with the jakarta specification?

It would be great to hear your opinion on what to do if there are issues with JPA implementations that do not comply with the spec or use features that are not yet supported.

-- korean
저도 이전에 EXTRACT 함수를 구현해볼까 싶어서, 사전에 몇가지 테스트를 해보다가 지금은 회사 업무로 인해 보류한 상태였는데, EXTRACT 함수 지원과 관련된 글이 보이길래 문의드려봅니다.

제가 몇가지 확인해봤을땐 Kotlin JDSL에서 지원하는 JPA 구현체(Hibernate, EclipseLink)별로 jakarta 스펙(extract_datetime_part)을 준수하지 않는것들도 있고,  일부 기능은 아직 지원하지 않는것을 확인했습니다. 또한 현재 Kotlin JDSL 프로젝트 Test 환경 구성(h2 driver, dialect) 기준에서는 올바르게 작동하지 않는 기능들도 있었습니다.

이런 경우에 Kotlin JDSL에서 jakarta 스펙만을 준수하는 JDSL API를 제공하면, 사용자가 스펙을 준수하지 않은 JPA구현체를 사용한다거나, 아직 지원하지 않는 기능들을 사용할 경우, 런타임에 올바르게 작동되지 않을수있겠지만, Kotlin JDSL에서는 그냥 jakarta spec만 준수하는 형태로 JDSL API를 제공해도 괜찮은건가요?

이렇게 JPA구현체에서 스펙을 준수하지 않거나 아직 지원하지 않는 기능 등으로 인한 문제가 발생하는 경우에는 어떻게 하는게 좋을지 의견주시면 좋을것같습니다.

**Comment by shouwn** [comment]
@erie0210, @waahhh thanks for the conversation. 

As waahhh said, EXTRACT is a db and implementation dependent feature, so we didn't plan to support it. This is also the same for CAST.

It is not possible for the Kotlin JDSL to provide all functions, because some interfaces depend on the implementation or DB. 

The Kotlin JDSL provides only those functions that can work in general. However, you can be sure that some functions will be available in your environment. To support this, Kotlin JDSL has chosen a structure that makes it easy to add functions. If you want to use some functions that depend on your implementation and DB, we would like to guide you in the way of creating your own DSL by inheriting the Jpql class. 

However, there are some features that the Kotlin JDSL doesn't support that would be too much work for the user to add. One example is the use of a subquery in a select clause, which is very useful to the user and is difficult to implement, so we've included it even though it's not supported in EclipseLink.

**Comment by shouwn** [comment]
Since there is no more conversation, this issue will be closed.
