### ISSUE TITLE
혹시 not in 절 지원안하나요? join 질문

### ISSUE THREAD

**Issue by kangMin6767** [line/kotlin-jdsl#72]
안녕하세요! queryDsl 만 써보다가 최근 코틀린-jdsl을 접하고, 최대한 바꿔볼려고 노력하고 있습니다. 변경작업 중에 몇가지 질문이 있어서 여쭤봅니다.

```
     List<Song> fetch = queryFactory
                .selectFrom(song)
                .where(
                        song.id.notIn(
                        JPAExpressions
                                .select(playlistSong.song.id)
                                .from(playlistSong)
                                .where(playlistSong.playlist.id.eq(playlistId)))
                )
                .limit(pageable.getPageSize())
                .offset(pageable.getOffset())
                .fetch();

```

queyrdsl로 만든 요런 쿼리를 kotiln jdsl로 바꿔볼려고 하는데

```

    val artistSongs = queryFactory.subquery<PlaylistSong>  {
        select(entity(PlaylistSong::class))
        from(entity(PlaylistSong::class))
        where(
            column(PlaylistSong::song).notEqual(Playlist())
        )
    }

 queryFactory.listQuery<Song> {
            select(entity(Song::class))
            from(entity(Song::class))
            where(
                column(Song::id).`in`(???)
            )

        }

```

단방향 연관관계로만 구성했고요. 
어떻게 비슷하게 만들어보려 했는데, 여기서 의문점이 연관관계 엔티티를 조회할때, 항상 객체참조를 넘겨줘야 외래키인 Id 값을 비교하는 것 같은데
querydsl로 id값만 넘겨줘서 비교하는 것도 가능한가요?
그러니까

```
  column(PlaylistSong::song::id) //요런 식으로 연관관계 엔티티의 필드를 조건으로 넘길 수 있을까요?

```
 
좋은 오픈소스 제공해주셔서 갑사합니다..

**Comment by cj848** [comment]
PlaylistSong::song::id is an impossible syntax in Kotlin. I'm sorry, but it's difficult to support that part.
This is because the :: syntax is a feature in the Kotlin language that automatically creates KProperty . It is difficult to create a syntax that is not in Kotlin, and it cannot be supported because it is not supported in the operator form.

-- korean
PlaylistSong::song::id 는 코틀린에서 불가능한 문법입니다. 아쉽긴 합니다만 해당 부분을 지원하긴 어렵습니다.
왜냐하면 :: 문법은 KProperty 를 자동으로 만들어주는 코틀린 언어로의 기능이기 때문입니다. 코틀린에 없는 문법을 만들어내기 어려우며 operator 형태로도 지원하지 않아 지원할 수가 없습니다.
