### ISSUE TITLE
Support of Sort.NullHandling from Spring

### ISSUE THREAD

**Issue by mikoaj-pe** [line/kotlin-jdsl#732]
Hi
I don't know if you are aware of this, but the findPage(pageable: Pageable) method does not fully cope with Sort from Spring. It manages to pass the direction and parameter name to the query, but loses information about NullHandling somewhere (NULLS_LAST etc.). So when I build Pageable with Sort looking like Sort.by(Order(DESC, "createdAt", NULLS_LAST)) - in query I only see "order by *.createdAt desc"

So I don't know if it's a bug or not yet implemented feature but I just want to let you know

**Comment by shouwn** [comment]
Hi mikoaj-pe.

I didn't realize this didn't work, my guess is that Spring doesn't support nulls_first or nulls_last yet. 
https://github.com/spring-projects/spring-data-jpa/issues/1280

When I looked at the code in Spring, it also didn't support this yet.
![image](https://github.com/line/kotlin-jdsl/assets/31586979/de0f4ebb-2410-475a-b6cb-fdd76cd8b609)

Probably because the Criteria API does not yet define interfaces for nulls_first or nulls_last.

Since Spring doesn't support it, it's unlikely that Kotlin JDSL will support it either.

If you want to use nulls_first or nulls_last, I recommend using the nullsFirst and nullsLast methods provided by Kotlin JDSL to handle them. 
![image](https://github.com/line/kotlin-jdsl/assets/31586979/16ca36f5-9a3d-46de-a8af-1f6abd04383f)

**Comment by shouwn** [comment]
I'll close this issue as there is no further conversation, but please reopen it if you need to discuss further.
